language: php

services:
#  - mysql
#  - memcached
#  - redis

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - pecl install mailparse
  - echo 'upload_tmp_dir = "/tmp"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer install --no-dev
  - cd tests/
  - composer install
  - vendor/bin/phpunit -c phpunit.cerb.platform.xml
