language: php

services:
#  - mysql
#  - memcached
#  - redis

php:
  - 7.2
  - 7.3
  - 7.4
  
before_install:
  - composer self-update --rollback
  - sudo apt-get -y install libyaml-dev

before_script:
  - printf "\n" | pecl install yaml
  - pecl install mailparse
  - echo 'upload_tmp_dir = "/tmp"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer install --no-dev
  - cd tests/
  - composer update
  - vendor/bin/phpunit -c phpunit.cerb.platform.xml
