# This file will merge with docker-compose when used like:
#   docker compose -f docker-compose.yml -f overrides/example.yml up --build

name: cerb-example

# Only keys defined here will override the base config
services:
  php-fpm:
    depends_on:
      - mysql
      - memcached
    volumes:
      - ../..:/var/www/html:ro
      # A custom framework file may be used for each environment
      - ./default/cerb.config.php:/var/www/html/framework.config.php:ro
      # A custom storage volume must be used for each environment
      - example-cerb-storage:/var/www/html/storage
  mysql:
    volumes:
      # A custom database volume must be used for each environment
      - example-cerb-db:/var/lib/mysql
  # This demonstrates adding additional containers
  memcached:
    image: memcached:latest

# External containers must be created with: docker volume create example
# The `external` setting prevents Docker Compose erasing them
volumes:
  example-cerb-storage:
    external: true
  example-cerb-db:
    external: true
